spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/awarddial?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: 123
#    druid数据库连接池
    druid:
#    最小连接池数量
      min-idle: 10
#    最大连接池数量
      max-active: 30
#    获取连接时最大等待时间，单位毫秒
      max-wait: 30000
#    物理连接初始化的时候执行的sql
      connection-init-sqls: set names utf8mb4
mybatis:
  mapper-locations: "classpath*:mapper/*.xml"
server:
  port: 8080